version: "3"
<<<<<<< HEAD
=======

>>>>>>> 617/main
services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app
    depends_on:
      - db
<<<<<<< HEAD
=======

>>>>>>> 617/main
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
<<<<<<< HEAD
=======

>>>>>>> 617/main
volumes:
  postgres_data: