"""add priority field for todo table

Revision ID: 1830f9275e77
Revises: 14aecf528c8a
Create Date: 2024-12-19 15:09:55.444878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1830f9275e77'
down_revision: Union[str, None] = '14aecf528c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'priority')
    # ### end Alembic commands ###
